### ISSUE TITLE
Adaptive icons don't seem to generate

### ISSUE THREAD

**Issue by andrepaulo-bit** [martiliones/icon-set-creator#17]
I've tried to run `iconset create` or an existing project, using the config from https://dev.to/martiliones/the-easiest-way-to-create-and-manage-app-icons-for-react-native-on-ios-android-52j0 
```js
module.exports = {
  imagePath: './icons/icon.png',

  adaptiveIconBackground: './icons/background.png',
  adaptiveIconForeground: './icons/foreground.png'
};
```
With the images provided in `/example` and it doesn't generate the adaptive icons.
I also tried in a fresh project (using the template `npx react-native init TestIconSetGenerator --template react-native-template-typescript --skip-install` and got the same result)
I'm using 0.1.4 as it was, and I also tried applying with patch #14 manually (because I needed the round icons)

**Comment by andrepaulo-bit** [comment]
These were the modifications to the android project: 
![image](https://user-images.githubusercontent.com/96743857/155102697-819c1437-8a5a-4368-9928-2b8e17bf0859.png)

**Comment by martiliones** [comment]
Fixed in TypeScript branch (I need some time to test it and publish)

For now you can use CLI options for a workaround
