### ISSUE TITLE
Various asset catalog build settings are clobbered when creating an icon set

### ISSUE THREAD

**Issue by rparrett** [martiliones/icon-set-creator#25]
By [this line of code](https://github.com/martiliones/icon-set-creator/blob/1c23d5b58a3fda171fc3f85075b63949f2ed0622/lib/creator/ios.ts#L162-L163).

There are [several build settings](https://developer.apple.com/documentation/xcode/build-settings-reference#Include-All-App-Icon-Assets) that contain the substring `ASSETCATALOG`, so this needs to be more specific. Probably an exact match for `ASSETCATALOG_COMPILER_APPICON_NAME`. I don't think any of the other build settings need their values changed.

(Otherwise, this tool seems to be working great for me, so thanks for publishing it!)

**Comment by martiliones** [comment]
Thanks for contributing to the project!

I published a new version (icon-set-creator@v1.1.16) to the npm registry that should resolve this issue. Feel free to reopen the issue if you have any question or you think the bug still exists.
