### ISSUE TITLE
Round icons not generated

### ISSUE THREAD

**Issue by MZabih** [martiliones/icon-set-creator#7]
Hi, I have used this plugin and it helped me to generate icons for both iOS and android. I have just one query it is not generating round icons for android app. as it is still getting the same old default icons. Is there any work around which can generate round icons and add them automatically for android?

**Comment by Chasty** [comment]
@MZabih any update

**Comment by martiliones** [comment]
@Chasty I will look today

**Comment by asgu** [comment]
same question

**Comment by martinmidtsund** [comment]
@martiliones  Thank you for a nice library! Round icons would be great, there are a couple of PR's that seem to handle this?

**Comment by martiliones** [comment]
Support for generating the round icons now available in the typescript branch. I need a few days to test all the features before I can merge it in master.

**Comment by martiliones** [comment]
I published `1.0.0` in the npm

https://www.npmjs.com/package/icon-set-creator

**Comment by martiliones** [comment]
@martinmidtsund Unfortunately, I couldn't merge the PRs (see #14)

**Comment by martinmidtsund** [comment]
@martiliones No worries, I see you have it on the typescript branch so it's not far away anyhow, great work! :D
