### ISSUE TITLE
Error when trying to generate icons for Android and iOS

### ISSUE THREAD

**Issue by designervoid** [martiliones/icon-set-creator#8]
I have tried to call command in my console - `iconset create ./icon.png`.
Next log was displayed in the console:
```
/usr/local/lib/node_modules/icon-set-creator/lib/utils/android.js:253
      return line.replaceAll(/android:icon="[^"]*(\\"[^"]*)*"/g,
                  ^

TypeError: line.replaceAll is not a function
    at /usr/local/lib/node_modules/icon-set-creator/lib/utils/android.js:253:19
    at Array.map (<anonymous>)
    at transformAndroidManifestIcon (/usr/local/lib/node_modules/icon-set-creator/lib/utils/android.js:243:34)
    at /usr/local/lib/node_modules/icon-set-creator/lib/utils/android.js:276:27
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:73:3)
```

I have replaced the `[string].replaceAll` with the `[string].replace` in the file `/usr/local/lib/node_modules/icon-set-creator/lib/utils/android.js: 253: 19`.
   Icons for `Android` have been generated successfully.
   Then the same error was repeated for `iOS`:
```
   /usr/local/lib/node_modules/icon-set-creator/lib/utils/ios.js:137
            lines[i] = line.replaceAll(/=(.*);/g, `= ${iconName};`);
                            ^

TypeError: line.replaceAll is not a function
    at /usr/local/lib/node_modules/icon-set-creator/lib/utils/ios.js:137:29
    at FSReqCallback.readFileAfterClose [as oncomplete] (internal/fs/read_file_context.js:73:3)
```
I have replaced the `[string].replaceAll` with the `[string].replace` in the file `/usr/local/lib/node_modules/icon-set-creator/lib/utils/ios.js:137:29`.
   Icons for `iOS` have been generated successfully.

**Comment by martiliones** [comment]
Nice catch! You can check the latest release (0.1.3), it should fix this issue

**Comment by designervoid** [comment]
https://github.com/martiliones/icon-set-creator/commit/5f08006fc3b37681113ca993b5f54c40a200b343
